name: Rust - Build, Test, Run

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  AOC_COOKIE: ${{ secrets.AOC_COOKIE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: AOCF Cookie Setup
        run: echo "$AOC_COOKIE" > ./.aocf/cookie && cat ./.aocf/cookie
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run AOC day 15
        run: cargo run --bin day15
      - name: Run AOC day 16
        run: cargo run --bin day16
