name: Rust - Build, Test, Run

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  AOC_COOKIE: ${{ secrets.AOC_COOKIE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install aocf_cli from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: aocf_cli
      - name: AOCF Cookie Setup
        run: aocf set-cookie $AOC_COOKIE
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run AOC day 15
        run: cargo run --bin day15
      - name: Run AOC day 16
        run: cargo run --bin day16
